package sample

import javafx.scene.control.ChoiceDialog
import java.util.Optional
import javafx.scene.control.Label
global javafx.scene.control.Label resultLabel

declare Option
    text: String
end

declare Question extends Option
    options: Option[]
end

declare Answer extends Option
    question: Question
end

declare Solution extends Option
    finalAnswer: String
end

function Option showOptions(Question q){
    String[] options = new String[q.getOptions().length];

    for(int i = 0; i < q.getOptions().length; i++){
        options[i] = q.getOptions()[i].getText();
    }
    ChoiceDialog<String> dialog = new ChoiceDialog<>(options[0], options);

    dialog.setTitle("Question");
    dialog.setHeaderText(q.getText());
    dialog.setContentText("Answer:");

    Optional<String> result = dialog.showAndWait();
    if(result.isPresent()){
        for(int i = 0; i < q.getOptions().length; i++){
            if(q.getOptions()[i].getText() == result.get()){
                return q.getOptions()[i];
            }
        }
    }
    return null;
 }

rule "Insert initial question"
    when
    then
        Question q = new Question();
        q.setText("Who are you watching it with?");
        Option[] answers =  {
                new Answer("My main squeeze", q),
                new Answer("My girlfriends", q),
                new Answer("My family", q)
        };
        q.setOptions(answers);
        insert(q);
end

rule "Show options on new question"
    when
        q : Question()
    then
        insert(showOptions(q));
end

rule "Show result on solution"
    when
        s : Solution()
    then
        resultLabel.setText("The result is: " + s.getFinalAnswer());
end

rule "Do you care if he enjoys it?"
    when
        Answer(question.text == "Who are you watching it with?") and
        Answer(text == "My main squeeze")
    then
        Question q = new Question();
        q.setText("Do you care if he enjoys it?");
        Option[] answers =  {
                new Solution("No", "The Notebook"),
                new Answer("Yes", q)
        };
        q.setOptions(answers);
        insert(q);
end

rule "Anyone recently getting over a breakup?"
    when
        Answer(question.text == "Who are you watching it with?") and
        Answer(text == "My girlfriends")
    then
        Question q = new Question();
        q.setText("Anyone recently getting over a breakup?");
        Option[] answers =  {
                new Answer("We're good!", q),
                new Answer("Let's avoid the heartache!", q)
        };
        q.setOptions(answers);
        insert(q);
end

rule "Do you like animation?"
    when
        Answer(question.text == "Who are you watching it with?") and
        Answer(text == "My family")
    then
        Question q = new Question();
        q.setText("Do you like animation?");
        Option[] answers =  {
                new Answer("Yes", q),
                new Answer("No", q)
        };
        q.setOptions(answers);
        insert(q);
end

rule "Action packed or thought provoking?"
    when
        Answer(question.text == "Do you care if he enjoys it?") and
        Answer(text == "Yes")
    then
        Question q = new Question();
        q.setText("Action packed or thought provoking?");
        Option[] answers =  {
                new Answer("I love explosions!", q),
                new Answer("Brains & beauty!", q),
                new Answer("Let's stick to the \"corn\" in \"romcom\"", q)
        };
        q.setOptions(answers);
        insert(q);
end

rule "Do you want to cry?"
    when
        Answer(question.text == "Anyone recently getting over a breakup?") and
        Answer(text == "We're good!")
    then
        Question q = new Question();
        q.setText("Do you want to cry?");
        Option[] answers =  {
                new Answer("Load up on the waterproof mascara!", q),
                new Answer("I'd rather not", q)
        };
        q.setOptions(answers);
        insert(q);
end

rule "Would a hunky male help?"
    when
        Answer(question.text == "Anyone recently getting over a breakup?") and
        Answer(text == "Let's avoid the heartache!")
    then
        Question q = new Question();
        q.setText("Would a hunky male help?");
        Option[] answers =  {
                new Answer("I prefer a mystery man", q),
                new Answer("Yes please!", q)
        };
        q.setOptions(answers);
        insert(q);
end

rule "Pixar or disney?"
    when
        Answer(question.text == "Do you like animation?") and
        Answer(text == "Yes")
    then
        Question q = new Question();
        q.setText("Pixar or disney?");
        Option[] answers =  {
                new Answer("Pixar", q),
                new Answer("Disney", q)
        };
        q.setOptions(answers);
        insert(q);
end

rule "Do holidays make you swoon?"
    when
        Answer(question.text == "Do you like animation?") and
        Answer(text == "No")
    then
        Question q = new Question();
        q.setText("Do holidays make you swoon?");
        Option[] answers =  {
                new Answer("I wish it was Christmas everyday", q),
                new Answer("Not really", q)
        };
        q.setOptions(answers);
        insert(q);
end

rule "Military fan?"
    when
        Answer(question.text == "Action packed or thought provoking?") and
        Answer(text == "I love explosions!")
    then
        Question q = new Question();
        q.setText("Military fan?");
        Option[] answers =  {
                new Solution("About face!", "Top Gun"),
                new Answer("No", q)
        };
        q.setOptions(answers);
        insert(q);
end

rule "Starring an IT girl?"
    when
        Answer(question.text == "Action packed or thought provoking?") and
        Answer(text == "Brains & beauty!")
    then
        Question q = new Question();
        q.setText("Starring an IT girl?");
        Option[] answers =  {
                new Solution("Yes", "Silver Linings Playbook"),
                new Answer("No", q)
        };
        q.setOptions(answers);
        insert(q);
end

rule "Judd Apatow film?"
    when
        Answer(question.text == "Action packed or thought provoking?") and
        Answer(text == "Let's stick to the \"corn\" in \"romcom\"")
    then
        Question q = new Question();
        q.setText("Starring an IT girl?");
        Option[] answers =  {
                new Answer("Yes, please!", q),
                new Answer("Pass", q)
        };
        q.setOptions(answers);
        insert(q);
end

rule "Do you like Tim Burton?"
    when
        Answer(question.text == "Would a hunky male help?") and
        Answer(text == "I prefer a mystery man")
    then
        Question q = new Question();
        q.setText("Do you like Tim Burton?");
        Option[] answers =  {
                new Solution("Bring on the darkness!", "Edward Scissorhands"),
                new Answer("Something less morose", q)
        };
        q.setOptions(answers);
        insert(q);
end

rule "Is it Ryan Gosling?"
    when
        Answer(question.text == "Would a hunky male help?") and
        Answer(text == "Yes please!")
    then
        Question q = new Question();
        q.setText("Is it Ryan Gosling?");
        Option[] answers =  {
                new Answer("Duh", q),
                new Answer("Over Him", q)
        };
        q.setOptions(answers);
        insert(q);
end

rule "With robots or humans?"
    when
        Answer(question.text == "Pixar or disney?") and
        Answer(text == "Pixar")
    then
        Question q = new Question();
        q.setText("With robots or humans?");
        Option[] answers =  {
                new Solution("Robots", "WALL-E"),
                new Solution("Humans", "Up")
        };
        q.setOptions(answers);
        insert(q);
end

rule "Are you a lover or a fighter?"
    when
        Answer(question.text == "Pixar or disney?") and
        Answer(text == "Disney")
    then
        Question q = new Question();
        q.setText("Are you a lover or a fighter?");
        Option[] answers =  {
                new Solution("Fighter", "Tangled"),
                new Solution("Lover", "Beauty and the Beast")
        };
        q.setOptions(answers);
        insert(q);
end

rule "Do you like black & white films?"
    when
        Answer(question.text == "Do holidays make you swoon?") and
        Answer(text == "I wish it was Christmas everyday")
    then
        Question q = new Question();
        q.setText("Do you like black & white films?");
        Option[] answers =  {
               new Solution("Always love the classics", "It's a Wonderful Life"),
               new Answer("Maybe something more modern", q)
        };
        q.setOptions(answers);
        insert(q);
end

rule "Little kids or young adults?"
    when
        Answer(question.text == "Do holidays make you swoon?") and
        Answer(text == "Not really")
    then
        Question q = new Question();
        q.setText("Little kids or young adults?");
        Option[] answers =  {
                new Answer("Something for the kiddies, please!", q),
                new Answer("We have teens in the house", q)
        };
        q.setOptions(answers);
        insert(q);
end

rule "Male or female lead?"
     when
         Answer(question.text == "Military fan?") and
         Answer(text == "No")
     then
         Question q = new Question();
         q.setText("Male or female lead?");
         Option[] answers =  {
                 new Solution("Girls have muscle too!", "Mr. and Mrs. Smith"),
                 new Solution("Male", "Bourne identity")
         };
         q.setOptions(answers);
         insert(q);
end

rule "Foreign film?"
     when
         Answer(question.text == "Starring an IT girl?") and
         Answer(text == "No")
     then
         Question q = new Question();
         q.setText("Foreign film?");
         Option[] answers =  {
                 new Solution("Oui", "Amélie"),
                 new Answer("No", q)
         };
         q.setOptions(answers);
         insert(q);
end

rule "Guys only?"
     when
         Answer(question.text == "Judd Apatow film?") and
         Answer(text == "Pass")
     then
         Question q = new Question();
         q.setText("Guys only?");
         Option[] answers =  {
                 new Answer("Bromance is the best", q),
                 new Answer("Girl Power!", q)
         };
         q.setOptions(answers);
         insert(q);
 end

rule "Are thieves involved?"
    when
        Answer(question.text == "Do you like Tim Burton?") and
        Answer(text == "Something less morose")
    then
        Question q = new Question();
        q.setText("Are thieves involved?");
        Option[] answers =  {
             new Solution("I like a bad guy, but not a criminal", "Gone With the Wind"),
             new Answer("I love danger", q)
        };
        q.setOptions(answers);
    insert(q);
end

rule "Indie eye candy or classic hunks?"
    when
        Answer(question.text == "Is it Ryan Gosling?") and
        Answer(text == "Over Him")
    then
        Question q = new Question();
        q.setText("Indie eye candy or classic hunks?");
        Option[] answers =  {
             new Solution("Indie", "500 Days of Summer"),
             new Answer("Can't argue with a classic", q)
        };
        q.setOptions(answers);
        insert(q);
end

rule "Is Gosling head over heels in love?"
    when
        Answer(question.text == "Is it Ryan Gosling?") and
        Answer(text == "Duh")
    then
        Question q = new Question();
        q.setText("Is Gosling head over heels in love?");
        Option[] answers =  {
             new Answer("If it's not starring me then no", q),
             new Solution("Yes", "Lars and the Real Girl")
        };
        q.setOptions(answers);
        insert(q);
end

rule "How many love triangles?"
    when
        Answer(question.text == "Do you like black & white films?") and
        Answer(text == "Maybe something more modern")
    then
        Question q = new Question();
        q.setText("How many love triangles?");
        Option[] answers =  {
               new Solution("More than two and it's hard to follow", "The holiday"),
               new Solution("I love complexity", "Love Actually")
        };
        q.setOptions(answers);
        insert(q);
end

rule "How about a princess movie?"
    when
        Answer(question.text == "Little kids or young adults?") and
        Answer(text == "Something for the kiddies, please!")
    then
        Question q = new Question();
        q.setText("How about a princess movie?");
        Option[] answers =  {
                new Solution("My son will barf", "Moonrise kingdom"),
                new Solution("The girls would love that", "Enchanted"),
                new Solution("Something gender neutral", "The Princess Bride")
        };
        q.setOptions(answers);
        insert(q);
end

rule "Classic or 21st century story?"
    when
        Answer(question.text == "Little kids or young adults?") and
        Answer(text == "We have teens in the house")
    then
        Question q = new Question();
        q.setText("Classic or 21st century story?");
        Option[] answers =  {
                new Answer("Let's teach them a thing or two", q),
                new Answer("They roll their eyes at anything \"old\"", q)
        };
        q.setOptions(answers);
        insert(q);
end


