package sample

import javafx.scene.control.ChoiceDialog
import java.util.Optional
import javafx.scene.control.Label
global javafx.scene.control.Label resultLabel

declare Option
    text: String
end

declare Question extends Option
    options: Option[]
end

declare Answer extends Option
    question: Question
end

declare Solution extends Option
    finalAnswer: String
end

function Option showOptions(Question q){
    String[] options = new String[q.getOptions().length];

    for(int i = 0; i < q.getOptions().length; i++){
        options[i] = q.getOptions()[i].getText();
    }
    ChoiceDialog<String> dialog = new ChoiceDialog<>(options[0], options);

    dialog.setTitle("Pytanie");
    dialog.setHeaderText(q.getText());
    dialog.setContentText("Odpowiedź");

    Optional<String> result = dialog.showAndWait();
    if(result.isPresent()){
        for(int i = 0; i < q.getOptions().length; i++){
            if(q.getOptions()[i].getText() == result.get()){
                return q.getOptions()[i];
            }
        }
    }
    return null;
 }

rule "Insert initial question"
    when
    then
        Question q = new Question();
        q.setText("Who are you watching it with?");
        Option[] answers =  {
                new Answer("My main squeeze", q),
                new Answer("My girlfriends", q),
                new Answer("My family", q)
        };
        q.setOptions(answers);
        insert(q);
end

rule "Show options on new question"
    when
        q : Question()
    then
        insert(showOptions(q));
end

rule "Show result on solution"
    when
        s : Solution()
    then
        resultLabel.setText("The result is: " + s.getFinalAnswer());
end

rule "Do you care if he enjoys it?"
    when
        Answer(question.text == "Who are you watching it with?") and
        Answer(text == "My main squeeze")
    then
        Question q = new Question();
        q.setText("Do you care if he enjoys it?");
        Option[] answers =  {
                new Solution("No", "The Notebook"),
                new Answer("Yes", q)
        };
        q.setOptions(answers);
        insert(q);
end
